### ISSUE TITLE
Unable to send ping to broadcast address: "No route to host" error

### ISSUE THREAD

**Issue by shafayeatsumit** [sincerely-manny/expo-gbping#1]
Thank you for making this package! The rest of the packages are so outdated, this is going to be a life saver.

ERROR: The application is failing to send ping requests to broadcast addresses with the following error:

`(NOBRIDGE) ERROR [Error: Failed to send ping: The operation couldn't be completed. No route to host]`

This occurs when the application attempts to ping broadcast addresses (likely 255.255.255.255 or subnet broadcast addresses).

**Comment by sincerely-manny** [comment]
Hey!

Thank you for the kind words! I’m glad to hear the package is useful.

Regarding the error you’re seeing when sending ping requests to broadcast addresses (255.255.255.255 or subnet-specific broadcasts) — I’ve identified the issue. The wrapper currently rejects the entire operation after the first failed ping, which isn’t ideal for broadcast scenarios where many responses (or none) are expected.

I think I can add a method that collects and returns all results for a broadcast ping (via subscription/event maybe?), rather than failing early. I’ll update this thread once it’s implemented.

Thanks again for reporting this!

**Comment by sincerely-manny** [comment]
1d53d48232e71cb46709fccea3544a3ba8650874

And one library vendoring later we're done. Turns out broadcast pinging was already broken in the GBPing library. Should be working fine now. You can try v0.3.0.

**Comment by shafayeatsumit** [comment]
Whoa, that was a super fast reply — really appreciate it, man! I just tried the latest version of the package on the Simulator and it works perfectly. But on a real device, the broadcast ping doesn’t seem to work (still getting The operation couldn't be completed.No route to host). Do you know if it needs any special entitlements or something? I figure it must be possible since the [Ping Network Utility](https://apps.apple.com/us/app/ping-network-utility/id576773404) app can do it. Let me know if you’ve come across this before.

**Comment by sincerely-manny** [comment]
In my case, pinging 192.168.1.255 works fine on a real device, but 255.255.255.255 unfortunately does not. It’s possible it worked at some point but may have broken later—figuring that out would require digging deeper into the GBPing library, but I’m not that comfortable with Objective-C 😅

It’s also possible that iOS has some (security-related?) limitations in its network stack that I’m not fully aware of.

If I were to build a proper network ping utility, I’d probably use [NWBrowser](https://developer.apple.com/documentation/network/nwbrowser) (which does require special permissions) to discover devices on the network, and then ping them individually.
